domain:
  type: MultibandedFrequencyDomain
  num_samples_band_generation: 10
  base_domain:
    type: FrequencyDomain
    f_min: 20.0
    f_max: 1024.0
    delta_f: 0.00390625 # = 1/256
  multibanding_method: "adaptive"
  min_num_bins_per_period: 16
  delta_f_max: 2.0
#
#domain:
#  type: MultibandedFrequencyDomain
#  bands:
#  - [20.001953125, 20.462890625, 0.0078125]
#  - [20.474609375, 28.240234375, 0.015625]
#  - [28.263671875, 37.107421875, 0.03125]
#  - [37.154296875, 50.591796875, 0.0625]
#  - [50.685546875, 62.185546875, 0.125]
#  - [62.373046875, 114.623046875, 0.25]
#  - [114.998046875, 234.498046875, 0.5]
#  - [235.248046875, 389.248046875, 1.0]
#  - [390.748046875, 1022.748046875, 2.0]
#  window_factor: null
#  base_domain:
#    type: FrequencyDomain
#    f_min: 20.0
#    f_max: 1024.0
#    delta_f: 0.00390625
#    window_factor: null

#domain:
#  type: FrequencyDomain
#  f_min: 20.0
#  f_max: 1024.0
#  delta_f: 0.00390625 # = 1/256

waveform_generator:
  approximant: IMRPhenomPv2_NRTidal
#  approximant: IMRPhenomXPHM
  f_ref: 10.0

intrinsic_prior:
  # to add lamba_1/2, check line 244 in https://github.com/lscsoft/bilby/blob/b1e02f1dfae03d4939cae9c95eff300c22919689/bilby/gw/source.py#L244
  mass_1: bilby.core.prior.Constraint(minimum=1.0, maximum=2.5)
  mass_2: bilby.core.prior.Constraint(minimum=1.0, maximum=2.5)
  chirp_mass: bilby.gw.prior.UniformInComponentsChirpMass(minimum=1.0, maximum=2.0)
  mass_ratio: bilby.gw.prior.UniformInComponentsMassRatio(minimum=0.125, maximum=1.0)
  phase: default
  a_1: bilby.core.prior.Uniform(minimum=0.0, maximum=0.99)
  a_2: bilby.core.prior.Uniform(minimum=0.0, maximum=0.99)
  tilt_1: default
  tilt_2: default
  phi_12: default
  phi_jl: default
  theta_jn: default
  lambda_1: bilby.core.prior.Uniform(minimum=0.0, maximum=5000)
  lambda_2: bilby.core.prior.Uniform(minimum=0.0, maximum=5000)
  # Reference values for fixed (extrinsic) parameters. These are needed to generate a waveform.
  luminosity_distance: 100.0  # Mpc
  geocent_time: 0.0  # s

# Dataset size
num_samples: 10000

## Save a compressed representation of the dataset
compression:
  whitening: aLIGO_ZERO_DET_high_P_asd.txt
  phase_heterodyning:
    order: 0
  svd:
    # Truncate the SVD basis at this size. No truncation if zero.
    size: 250
    num_training_samples: 50000
    num_validation_samples: 10000
