domain:
  type: FrequencyDomain
  f_min: 20.0
  f_max: 1024.0
  delta_f: 0.00390625 # = 1/256

waveform_generator:
  approximant: IMRPhenomPv2_NRTidal
  f_ref: 10.0

intrinsic_prior:
  # to add lamba_1/2, check line 244 in https://github.com/lscsoft/bilby/blob/b1e02f1dfae03d4939cae9c95eff300c22919689/bilby/gw/source.py#L244
  mass_1: bilby.core.prior.Constraint(minimum=1.0, maximum=2.5)
  mass_2: bilby.core.prior.Constraint(minimum=1.0, maximum=2.5)
  chirp_mass: bilby.gw.prior.UniformInComponentsChirpMass(minimum=1.0, maximum=2.0)
  mass_ratio: bilby.gw.prior.UniformInComponentsMassRatio(minimum=0.125, maximum=1.0)
  phase: default
  a_1: bilby.core.prior.Uniform(minimum=0.0, maximum=0.99)
  a_2: bilby.core.prior.Uniform(minimum=0.0, maximum=0.99)
  tilt_1: default
  tilt_2: default
  phi_12: default
  phi_jl: default
  theta_jn: default
  # Reference values for fixed (extrinsic) parameters. These are needed to generate a waveform.
  luminosity_distance: 100.0  # Mpc
  geocent_time: 0.0  # s

# Dataset size
num_samples: 100

## Save a compressed representation of the dataset
#compression:
#  svd:
#    # Truncate the SVD basis at this size. No truncation if zero.
#    size: 200
#    num_training_samples: 50000
#    num_validation_samples: 10000
#  whitening: aLIGO_ZERO_DET_high_P_asd.txt